services:
  python-app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    ports:
      - "${MONGO_INITDB_PORT}:27017"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${POSTGRES_PORT}:5432"

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
