services:
  python-app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
      - redis
    restart: on-failure:5
    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    command: uvicorn --factory src.api.app:get_app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    ports:
      - "${MONGO_INITDB_PORT}:27017"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network
    ports:
      - "${REDIS_PORT}:6379"


  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.infra.celery.tasks.app worker --loglevel=info
    depends_on:
      - redis
      - postgres
      - mongo
      - python-app
    environment:
      - CELERY_BROKER=${BROKER}://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=${BROKER}://${REDIS_HOST}:${REDIS_PORT}/0
    volumes:
      - .:/app
    networks:
      - app_network

  # Celery Beat (для планирования задач)
  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.infra.celery.client beat --loglevel=info
    depends_on:
      - redis
      - postgres
      - mongo
      - python-app
    environment:
      - CELERY_BROKER=${BROKER}://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=${BROKER}://${REDIS_HOST}:${REDIS_PORT}/0
    volumes:
      - .:/app
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
