from src.common.filters.pagination import PaginationFilters
from src.domain.entities.base import BaseEntity


class MongoRepo:

    def add_one(self, entity: BaseEntity): ...

    def get_one(self, entity: BaseEntity): ...

    def get_many(self, entity: BaseEntity, filters: PaginationFilters): ...

    def delete_one(self, entity: BaseEntity): ...

    def update_one(self, entity: BaseEntity): ...
